const facultyData = [
  {
    "id": 41,
    "name": "Ms. Aashka Raval",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Aashka.Raval@sot.pdpu.ac.in",
    "photo": "images/faculty/aashkaraval.jpeg",
    "qualification": "M.Tech",
    "phdSubject": "",
    "college": "PDEU",
    "researchInterest": "Computer Engineering, Machine Learning",
    "phone": "81601 30780",
    "cabin": "E block 2nd floor Cubical",
    "timetable": "images/faculty/aashkatt.jpeg"
  },
  {
    "id": 5,
    "name": "Dr. Aditya Shastri",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Aditya.Shastri@sot.pdpu.ac.in",
    "photo": "images/faculty/adityashastri.jpeg",
    "qualification": "Ph.D, M.Tech., B.Tech.",
    "phdSubject": "Computer Science and Engineering",
    "college": "IIT Indore",
    "researchInterest": "Computational Science and Engineering, Machine Learning Algorithms for Bioinformatics, Medical Imaging Data",
    "phone": "9420561379",
    "cabin": "F block 5th floor Cubical",
    "timetable": "images/faculty/adityatt.jpeg"
  },
  {
    "id": 6,
    "name": "Dr. Amit Singh",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Amit.Singh@sot.pdpu.ac.in",
    "photo": "images/faculty/amitsingh.jpeg",
    "qualification": "Ph.D, M.Tech., B.Tech.",
    "phdSubject": "Computer Science",
    "college": "Central University of Rajasthan, Ajmer",
    "researchInterest": "Network Coding in Wireless Ad hoc Networks, IoT, Data Science, Machine Learning",
    "phone": "82907 27943",
    "cabin": "E 216",
    "timetable": "images/faculty/amittt.jpeg"
  },
  {
    "id": 7,
    "name": "Dr. Amitava Choudhury",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Amitava.Choudhury@sot.pdpu.ac.in",
    "photo": "images/faculty/amitavachoudhury.jpeg",
    "qualification": "B.Tech., M.Tech., Ph.D",
    "phdSubject": "Computer Science and Technology",
    "college": "Indian Institute of Engineering Science and Technology. Shibpur",
    "researchInterest": "Computational Geometry, Pattern Recognition, Character Recognition, Machine Learning",
    "phone": "8902691510",
    "cabin": "F block 5th floor Cubical",
    "timetable": "images/faculty/amitavatt.jpeg"
  },
  {
    "id": 8,
    "name": "Dr. Archana Nigam",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Archana.Nigam@sot.pdpu.ac.in",
    "photo": "images/faculty/archananigam.jpeg",
    "qualification": "Ph.D, M.Tech",
    "phdSubject": "Intelligent Transportation Systems",
    "college": "DA-IICT Gandhinagar",
    "researchInterest": "Machine Learning, ITS",
    "phone": "92271 01906",
    "cabin": "F Block 1st Floor Cubical",
    "timetable": "images/faculty/archanatt.jpeg"
  },
  {
    "id": 9,
    "name": "Dr. Ashish Patel",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Ashish.Patel1@sot.pdpu.ac.in",
    "photo": "images/faculty/ashishpatel.jpeg",
    "qualification": "Ph.D, M.E., B.E.",
    "phdSubject": "Computer Engineering",
    "college": "PDEU",
    "researchInterest": "Smart Systems",
    "phone": "",
    "cabin": "F 205",
    "timetable": "images/faculty/ashishtt.jpeg"
  },
  {
    "id": 10,
    "name": "Dr. Azriel Henry",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Azriel.Henry@sot.pdpu.ac.in",
    "photo": "images/faculty/azrielhenry.jpeg",
    "qualification": "Ph.D, M.E",
    "phdSubject": "Cyber Security",
    "college": "Institute of Advanced Research, Gandhinagar",
    "researchInterest": "Cyber Security & AI",
    "phone": "88661 46303",
    "cabin": "F 305",
    "timetable": "images/faculty/azrieltt.jpeg"
  },
  {
    "id": 11,
    "name": "Dr. Bhoomi Bangoria",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Bhoomi.Bangoria@sot.pdpu.ac.in",
    "photo": "images/faculty/bhoomibangoria.jpeg",
    "qualification": "Ph.D, M.E., B.E.",
    "phdSubject": "Computer Engineering",
    "college": "Dr. Subhash University",
    "researchInterest": "Artificial Intelligence, Machine Learning, Data Science, Cyber Security, Deep Learning, Recommender Systems, Smart Cities",
    "phone": "9429363236",
    "cabin": "F block 6th floor Cubical",
    "timetable": "images/faculty/bhoomitt.jpeg"
  },
  {
    "id": 42,
    "name": "Ms. Chahat Gupta",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Chahat.Gupta@sot.pdpu.ac.in",
    "photo": "images/faculty/chahatgupta.jpeg",
    "qualification": "B.Tech., M.Tech.",
    "phdSubject": "",
    "college": "Guru Nanak Dev University, Amritsar, Punjab",
    "researchInterest": "AI, Communication Systems",
    "phone": "75087687338",
    "cabin": "F block 6th floor Cubical",
    "timetable": "images/faculty/chahattt.jpeg"
  },
  {
    "id": 12,
    "name": "Dr. Darshit Shah",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "darshit.shah@spt.pdpu.ac.in",
    "photo": "images/faculty/darshitshah.jpeg",
    "qualification": "B.Com., M.B.A, Ph.D",
    "phdSubject": "Management / Computer Applications",
    "college": "PDEU",
    "researchInterest": "Financial Markets, Behavioural Finance, Stock Market, Computer Programming",
    "phone": "9825874525",
    "cabin": "E 106",
    "timetable": "images/faculty/darshitt.jpeg"
  },
  {
    "id": 13,
    "name": "Dr. Davinder Paul Singh",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Davinder.Singh@sot.pdpu.ac.in",
    "photo": "images/faculty/davinderpaulsingh.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Computer Science and Engineering",
    "college": "Shri Mata Vaishno Devi University J&K",
    "researchInterest": "Machine Learning, Deep Learning, Bio-informatics, Computational Biology, AI",
    "phone": "70062 91893",
    "cabin": "E 215",
    "timetable": "images/faculty/davindertt.jpeg"
  },
  {
    "id": 14,
    "name": "Dr. Debabrata Swain",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Debabrata.Swain@sot.pdpu.ac.in",
    "photo": "images/faculty/debabrataswain.jpeg",
    "qualification": "B.Tech., M.Tech., Ph.D",
    "phdSubject": "Computer Science and Engineering",
    "college": "KIIT University",
    "researchInterest": "Machine Learning, Deep Learning, Natural Language Processing, Computer Architecture, Web Programming",
    "phone": "94202 82817",
    "cabin": "F block 3rd floor Cubical",
    "timetable": "images/faculty/debabratatt.jpeg"
  },
  {
    "id": 15,
    "name": "Dr. Hargeet Kaur",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Hargeet.Kaur@sot.pdpu.ac.in",
    "photo": "images/faculty/hargeetkaur.jpeg",
    "qualification": "B.Tech., M.Tech., Ph.D",
    "phdSubject": "Computer Science and Engineering",
    "college": "IIT Jodhpur",
    "researchInterest": "Quantum Information and Computation, Quantum Game Theory, Quantum Machine Learning",
    "phone": "7023790523",
    "cabin": "F block 3rd floor Cubical",
    "timetable": "images/faculty/hargeettt.jpeg"
  },
  {
    "id": 16,
    "name": "Dr. Himanshu Gajera",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Himanshu.Gajera@sot.pdpu.ac.in",
    "photo": "images/faculty/himanshugajera.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Computer Engineering",
    "college": "SVNIT, Surat",
    "researchInterest": "Deep Learning, Machine Learning, Medical Image Analysis, Computer Vision, Pattern Recognition",
    "phone": "99044 66120",
    "cabin": "F Block 5th floor Cubical",
    "timetable": "images/faculty/himanshutt.jpeg"
  },
  {
    "id": 17,
    "name": "Dr. Hiren Thakkar",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Hiren.Thakkar@sot.pdpu.ac.in",
    "photo": "images/faculty/hirenthakkar.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Computer Science and Information Engineering",
    "college": "Chang Gung University, Taiwan",
    "researchInterest": "Applied Machine Learning, Healthcare Data Analysis, Cloud Resource Management, Opinion Feature Mining",
    "phone": "9137474254",
    "cabin": "F Block 5th floor Cubical",
    "timetable": "images/faculty/hirenthakkar.jpeg"
  },
  {
    "id": 18,
    "name": "Dr. Kalgi Gandhi",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Kalgi.Gandhi@sot.pdpu.ac.in",
    "photo": "images/faculty/kalgigandhi.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Distributed Databases",
    "college": "DAU Gandhinagar",
    "researchInterest": "Databases, Edge Computing",
    "phone": "79843 80204",
    "cabin": "F 105",
    "timetable": "images/faculty/kalgitt.jpeg"
  },
  {
    "id": 19,
    "name": "Dr. Kaushal Shah",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Kaushal.Shah@sot.pdpu.ac.in",
    "photo": "images/faculty/kaushalshah.jpeg",
    "qualification": "Ph.D, M.E., B.E.",
    "phdSubject": "Computer Engineering",
    "college": "SVNIT",
    "researchInterest": "Blockchain Technology, Information Security, Data Structures, Smart Grid",
    "phone": "74956 63470",
    "cabin": "F block 5th floor Cubical",
    "timetable": "images/faculty/kaushaltt.jpeg"
  },
  {
    "id": 20,
    "name": "Dr. Ketan Sabale",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Ketan.Sabale@sot.pdpu.ac.in",
    "photo": "images/faculty/ketansabale.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Computer Science and Engineering",
    "college": "National Institute of Technology, Goa",
    "researchInterest": "IoT, WSN, MANET, Swarm Intelligence",
    "phone": "75889 44989",
    "cabin": "F block 5th floor Cubical",
    "timetable": "images/faculty/ketantt.jpeg"
  },
  {
    "id": 43,
    "name": "Ms. KomalSingh",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Komal.S@sot.pdpu.ac.in",
    "photo": "images/faculty/komalsingh.jpeg",
    "qualification": "M.E",
    "phdSubject": "",
    "college": "LDRP",
    "researchInterest": "",
    "phone": "85117 05400",
    "cabin": "F 305",
    "timetable": "images/faculty/komaltt.jpeg"
  },
  {
    "id": 21,
    "name": "Dr. Manish Paliwal",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Manish.Paliwal@sot.pdpu.ac.in",
    "photo": "images/faculty/manishpaliwal.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Software-Defined Networks, Computer Science and Engineering",
    "college": "VNIT Nagpur",
    "researchInterest": "Software-Defined Networks, Distributed Networks, Wireless Networks, Algorithms",
    "phone": "77449 35721",
    "cabin": "F block 5th floor Cubical",
    "timetable": "images/faculty/manishtt.jpeg"
  },
  {
    "id": 22,
    "name": "Dr. Meera Thapar Khanna",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Meera.Khanna@sot.pdpu.ac.in",
    "photo": "images/faculty/meerathaparkhanna.jpeg",
    "qualification": "Ph.D, M.Tech., B.Tech.",
    "phdSubject": "Image Processing and Computer Vision",
    "college": "IIT Delhi",
    "researchInterest": "Image Processing and Computer Vision, Perceptual Visual Information Processing",
    "phone": "9899595085",
    "cabin": "E 213",
    "timetable": "images/faculty/meeratt.jpeg"
  },
  {
    "id": 23,
    "name": "Dr. Nandini Modi",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Nandini.Modi@sot.pdpu.ac.in",
    "photo": "images/faculty/nandinimodi.jpeg",
    "qualification": "M.E., Ph.D, B.Tech.",
    "phdSubject": "Computer Science and Engineering",
    "college": "Chitkari University",
    "researchInterest": "Machine Learning, Deep Learning, Cognitive Computing, Neuroscience, Eye Tracking, NLP",
    "phone": "82839 21106",
    "cabin": "F block 3rd floor Cubical",
    "timetable": "images/faculty/nandinitt.jpeg"
  },
  {
    "id": 44,
    "name": "Ms. Nidhi Dubey",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "",
    "photo": "images/faculty/nidhidubey.jpeg",
    "qualification": "",
    "phdSubject": "Computer Science and Engineering",
    "college": "",
    "researchInterest": "",
    "phone": "",
    "cabin": "F 205",
    "timetable": "images/faculty/nidhitt.jpeg"
  },
  {
    "id": 45,
    "name": "Mr. Nisarg Patel",
    "designation": "Visiting Faculty",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "",
    "photo": "",
    "qualification": "",
    "phdSubject": "Computer Science and Engineering",
    "college": "",
    "researchInterest": "",
    "phone": "",
    "cabin": "",
    "timetable": "images/faculty/nisaragtt.jpeg"
  },
  {
    "id": 2,
    "name": "Dr. Nishant Doshi",
    "designation": "Associate Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Nishant.Doshi@sot.pdpu.ac.in",
    "photo": "images/faculty/nishantdoshi.jpeg",
    "qualification": "M.Tech., Ph.D",
    "phdSubject": "Computer Engineering, Cryptography",
    "college": "SVNIT, Surat",
    "researchInterest": "Algorithms, Cryptography, Remote User Authentication, Information Protection",
    "phone": "93761 83485",
    "cabin": "E block 2nd floor Cubical",
    "timetable": "images/faculty/nishanttt.jpeg"
  },
  {
    "id": 24,
    "name": "Dr. Payal Chaudhari",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Payal.Chaudhari@sot.pdpu.ac.in",
    "photo": "images/faculty/payalchaudhari.jpeg",
    "qualification": "Ph.D, M.E., B.E.",
    "phdSubject": "Information Security",
    "college": "Da-IICT Gandhinagar",
    "researchInterest": "Information Security, Network Security, Cryptography, Web Technology, Java Programming",
    "phone": "99091809127",
    "cabin": "E 215",
    "timetable": "images/faculty/payaltt.jpeg"
  },
  {
    "id": 25,
    "name": "Dr. Pooja Shah",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Pooja.Shah@sot.pdpu.ac.in",
    "photo": "images/faculty/poojashah.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Computer Science and Engineering",
    "college": "Nirma University",
    "researchInterest": "Image Processing, Cyber Security, AI, Digital Forensics, ML",
    "phone": "9825434173",
    "cabin": "F Block 1st floor Cubical",
    "timetable": "images/faculty/poojatt.jpeg"
  },
  {
    "id": 26,
    "name": "Dr. Punit Gupta",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Punit.Gupta@sot.pdpu.ac.in",
    "photo": "images/faculty/punitgupta.jpeg",
    "qualification": "Ph.D, M.Tech.",
    "phdSubject": "Cloud Computing Trust Management, Computer Science and Engineering",
    "college": "Jaypee University of Information Technology",
    "researchInterest": "Cloud Optimization, FOG, EDGE, IoT, Optimization, Cloud Computing",
    "phone": "98822 05191",
    "cabin": "F 105",
    "timetable": "images/faculty/punittt.jpeg"
  },
  {
    "id": 27,
    "name": "Dr. Rajeev Gupta",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Rajeev.Gupta@sot.pdpu.ac.in",
    "photo": "images/faculty/rajeevgupta.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science & Engineering",
    "college": "MANIT Bhopal",
    "researchInterest": "ML, DL & AI",
    "phone": "98939 44156",
    "cabin": "F block 1st floor Cubical",
    "timetable": "images/faculty/rajeevtt.jpeg"
  },
  {
    "id": 28,
    "name": "Dr. Rajendra Choudhary",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Rajendra.Choudhary@sot.pdpu.ac.in",
    "photo": "images/faculty/rajendrachoudhary.jpeg",
    "qualification": "Ph.D, M.Tech.",
    "phdSubject": "Computational Optimization",
    "college": "IIT Indore",
    "researchInterest": "Computational Optimization, Numerical Linear Algebra",
    "phone": "81090 66213",
    "cabin": "F block 5th floor Cubical",
    "timetable": "images/faculty/rajendratt.jpeg"
  },
  {
    "id": 29,
    "name": "Dr. Riddhi Thakkar",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Riddhi.Thakkar@sot.pdpu.ac.in",
    "photo": "images/faculty/riddhithakkar.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science & Engineering",
    "college": "Nirma University",
    "researchInterest": "",
    "cabin": "F 205",
    "timetable": "images/faculty/riddhitt.jpeg"
  },
  {
    "id": 3,
    "name": "Dr. Rutvij Jhaveri",
    "designation": "Associate Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Rutvij.Jhaveri@sot.pdpu.ac.in",
    "photo": "images/faculty/rutvijjhaveri.jpeg",
    "qualification": "Ph.D, M.Tech., B.E.",
    "phdSubject": "Computer Engineering",
    "college": "Charusat University",
    "researchInterest": "Software-Defined Networking, Routing Security, Smart Ecosystems",
    "phone": "",
    "cabin": "E 209/2",
    "timetable": "images/faculty/rutvijtt.jpeg"
  },
  {
    "id": 4,
    "name": "Dr. Samir Patel",
    "designation": "Associate Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Samir.Patel@sot.pdpu.ac.in",
    "photo": "images/faculty/samirpatel.jpeg",
    "qualification": "Ph.D, M.E., B.E.",
    "phdSubject": "Computer Engineering",
    "college": "Nirma University",
    "researchInterest": "Big Data Analytics, Parallel Computing, Data Processing and Mining",
    "phone": "9427401616",
    "cabin": "F block 2nd floor Cubical",
    "timetable": "images/faculty/samirtt.jpeg"
  },
  {
    "id": 30,
    "name": "Dr. Sanjeev Dwivedi",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Sanjeev.Dwivedi@sot.pdpu.ac.in",
    "photo": "images/faculty/sanjeevdwivedi.jpeg",
    "qualification": "Ph.D, M.Tech.",
    "phdSubject": "Computer Science and Engineering",
    "college": "IIIT, Naya Raipur",
    "researchInterest": "Authentication Techniques, Blockchain, Cryptographic Mechanisms, Data Security Protocols, Digital Twins, Metaverse",
    "phone": "70178 94130",
    "cabin": "F block 2nd floor Cubical",
    "timetable": "images/faculty/sanjeevtt.jpeg"
  },
  {
    "id": 31,
    "name": "Dr. Santosh Kumar Bharti",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Santosh.Bharti@sot.pdpu.ac.in",
    "photo": "images/faculty/santoshkumarbharti.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Computer Science and Engineering",
    "college": "National Institute of Technology, Rourkela",
    "researchInterest": "Natural Language Processing, Social Computing, Sentiment Analysis",
    "phone": "93382 62742",
    "cabin": "F block 1st floor cubical",
    "timetable": "images/faculty/santoshtt.jpeg"
  },
  {
    "id": 1,
    "name": "Dr. Shakti Mishra",
    "designation": "Associate Professor & Dean",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Shakti.Mishra@sot.pdpu.ac.in",
    "photo": "images/faculty/shaktimishra.jpeg",
    "qualification": "Ph.D, B.Tech.",
    "phdSubject": "Distributed Computing",
    "college": "MNNIT Allahabad",
    "researchInterest": "Distributed Computing, ML in Renewable Energy, Computational Data Science, Cloud Computing, Explainable & Reproducible AI",
    "phone": "98862 97927",
    "cabin": "E block ground floor admin",
    "timetable": "images/faculty/shaktitt.jpeg"
  },
  {
    "id": 32,
    "name": "Dr. Shilpa Pandey",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Shilpa.Pandey@sot.pdpu.ac.in",
    "photo": "images/faculty/shilpapandey.jpeg",
    "qualification": "Ph.D, M.Tech., B.Tech.",
    "phdSubject": "Computer Vision and Machine Learning",
    "college": "IIT Jodhpur",
    "researchInterest": "Document Image Analysis, Intelligent Forensic, Data Analytics, Deep Learning",
    "phone": "77909 15175",
    "cabin": "E 213",
    "timetable": "images/faculty/shilpatt.jpeg"
  },
  {
    "id": 33,
    "name": "Dr. Shivangi Surati",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Shivangi.Surati@sot.pdpu.ac.in",
    "photo": "images/faculty/shivangisurati.jpeg",
    "qualification": "Ph.D, M.E., B.E.",
    "phdSubject": "Computer Engineering",
    "college": "SVNIT, Surat",
    "researchInterest": "Advanced Algorithms, Machine Learning, Internet of Things, Language Processors",
    "phone": "9879120125",
    "cabin": "E 215",
    "timetable": "images/faculty/shivangitt.jpeg"
  },
  {
    "id": 34,
    "name": "Dr. Sidheswar Routray",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Sidheswar.Routray@sot.pdpu.ac.in",
    "photo": "images/faculty/sidheswarroutray.jpeg",
    "qualification": "Ph.D, M.Tech.",
    "phdSubject": "Computer Science and Engineering, Artificial Intelligence",
    "college": "KIIT University",
    "researchInterest": "Image Processing, Natural Language Processing, Artificial Intelligence, Machine Learning, Healthcare",
    "phone": "98615 95680",
    "cabin": "F 105",
    "timetable": "images/faculty/sidheswartt.jpeg"
  },
  {
    "id": 35,
    "name": "Dr. Sonam Nahar",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Sonam.Nahar@sot.pdpu.ac.in",
    "photo": "images/faculty/sonamnahar.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Computer Vision",
    "college": "DA-IICT",
    "researchInterest": "Computer Vision, Gait Recognition, Pattern Recognition, Stereo Matching, Machine Learning",
    "phone": "8118829552",
    "cabin": "F block 1st floor Cubical",
    "timetable": "images/faculty/sonamtt.jpeg"
  },
  {
    "id": 36,
    "name": "Dr. Sujit Kumar Das",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Sujit.Das@sot.pdpu.ac.in",
    "photo": "images/faculty/sujitkumardas.jpeg",
    "qualification": "B.Tech., M.E., Ph.D",
    "phdSubject": "Privacy Protection of Digital Images",
    "college": "Jadavpur University",
    "researchInterest": "Secret Sharing, Image Encryption, Steganography",
    "phone": "90519 03502",
    "cabin": "E block 2nd floor cubical",
    "timetable": "images/faculty/sujittt.jpeg"
  },
  {
    "id": 37,
    "name": "Dr. Tanmay Bhowmik",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Tanmay.Bhowmik@sot.pdpu.ac.in",
    "photo": "images/faculty/tanmaybhowmik.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Speech Processing",
    "college": "IIT Kharagpur",
    "researchInterest": "Speech Processing",
    "phone": "94764 09727",
    "cabin": "F block 1st floor Cubical",
    "timetable": "images/faculty/tanmaytt.jpeg"
  },
  {
    "id": 38,
    "name": "Dr. Trishna Paul",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Trishna.Paul@sot.pdpu.ac.in",
    "photo": "images/faculty/trishnapaul.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science and Engineering",
    "college": "BITS Pilani",
    "researchInterest": "Computer Engineering, Data Science, AI & ML",
    "phone": "70632 29292",
    "cabin": "F 305",
    "timetable": "images/faculty/trishnatt.jpeg"
  },
  {
    "id": 39,
    "name": "Dr. Utkarsh Tiwari",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Utkarsh.Tiwari@sot.pdpu.ac.in",
    "photo": "images/faculty/utkarshtiwari.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Hardware Security",
    "college": "IIIT, Naya Raipur",
    "researchInterest": "Hardware Security, Public Key Cryptography, FPGA Implementation, Post-Quantum Cryptography",
    "phone": "90981 59815",
    "cabin": "F block 3rd floor Cubical",
    "timetable": "images/faculty/utkarshtt.jpeg"
  },
  {
    "id": 40,
    "name": "Dr. Yogesh Kumar",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Yogesh.Kumar@sot.pdpu.ac.in",
    "photo": "images/faculty/yogeshkumar.jpeg",
    "qualification": "M.Tech., Ph.D",
    "phdSubject": "Speech Recognition System and Machine Learning, Computer Science and Engineering",
    "college": "Punjabi University, Patiala",
    "researchInterest": "Explainable AI (XAI), Natural Language Processing, Deep Learning and Federated Learning in Healthcare",
    "phone": "98883 10744",
    "cabin": "F block 5th floor Cubical",
    "timetable": "images/faculty/yogeshtt.jpeg"
  }
]